apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #minikube path where data will be retained even during restart: /mnt/data
    path: "/mnt/data/sonarqube/logs"
  claimRef:
    namespace: sonarqube
    name: sonarqube-data-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #minikube path where data will be retained even during restart: /mnt/data
    path: "/mnt/data/sonarqube/extensions"
  claimRef:
    namespace: sonarqube
    name: sonarqube-extensions-claim  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-logs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #minikube path where data will be retained even during restart: /mnt/data
    path: "/mnt/data/sonarqube/logs"
  claimRef:
    namespace: sonarqube
    name: sonarqube-logs-claim      