apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sonarqube
  name: sonarqube-data-claim
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sonarqube
  name: sonarqube-extensions-claim
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sonarqube
  name: sonarqube-logs-claim
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi